version: "3.3"
services:
  front:
    image: node:12.3.1
    working_dir: "/var/app"
    volumes:
      - "./:/var/app"
    restart: unless-stopped
    command: bash -c "node app.js"
    ports:
      - "3009:3009"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8089:80
    volumes:
      - /sessions
volumes:
  my-db:
